version: '3.7'
services:
  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile-nginx
  #   ports:
  #     - 8880:80
  #   volumes:
  #     - ./log/nginx/:/var/log/nginx/
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/wasm:/wasm
  #     - ./nginx/vuedist:/vuedist
  #   depends_on:
  #     - vuefront
  #     # - vuetest
  #   container_name: cubetrain-nginx

  vuefront:
    build:
      context: ./frontside
      dockerfile: Dockerfile
    ports:
      - 8881:8080
    volumes:
      - ./frontside:/frontside
    container_name: account-vuefront
    tty: true

