---
swagger: "2.0"
info:
  version: "apigw-myhome-account"
  title: "apigw-myhome-account"
host: "z6tw2evta4.execute-api.ap-northeast-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /api/health:
    get:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Health"
      x-amazon-apigateway-integration:
        responses:
          200:
            statusCode: "200"
            responseTemplates:
              application/json: "#set($inputRoot = $input.path('$'))\n{\n  \"status\"\
                \ : \"Health OK\"\n}"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "when_no_match"
        type: "mock"
  /api/balance:
    post:
      produces:
      - "application/json"
      parameters:
      - name: "tgt_date"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:055389889595:function:myhome-account-get-balance/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: aws_proxy
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  Dummy:
    type: "object"
    properties:
      status:
        type: "string"
  Empty:
    type: "object"
    title: "Empty Schema"
  Health:
    type: "object"
    title: "Health result"
    properties:
      status:
        type: "string"

