---
swagger: "2.0"
info:
  version: "apigw-myhome-account"
  title: "apigw-myhome-account"
host: "dummy.execute-api.ap-northeast-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /api/health:
    get:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Health"
      x-amazon-apigateway-integration:
        responses:
          200:
            statusCode: "200"
            responseTemplates:
              application/json: "#set($inputRoot = $input.path('$'))\n{\n  \"status\"\
                \ : \"Health OK\"\n}"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "when_no_match"
        type: "mock"
  /api/balance:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "tgt_date"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Balance"
        500:
          description: "Internal Error."
          schema:
            $ref: "#/definitions/Empty"
      security:
        - api_key: []
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:055389889595:function:myhome-account-get-balance/invocations"
        responses:
          default:
            statusCode: "200"
          .+:
            statusCode: "500"
        passthroughBehavior: "when_no_templates"
        requestTemplates:
          "application/json" : "{ \"tgt_date\": \"$input.params('tgt_date')\" }"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: aws
    post:
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Balance"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      security:
        - api_key: []
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:055389889595:function:myhome-account-post-balance/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: aws_proxy
  /api/kindmst:
    get:
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/KindMstList"
        500:
          description: "Internal Error."
          schema:
            $ref: "#/definitions/Empty"
      security:
        - api_key: []
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:055389889595:function:myhome-account-get-kindmst/invocations"
        responses:
          default:
            statusCode: "200"
          .+:
            statusCode: "500"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: aws_proxy
  /api/slip:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "tgt_date_from"
        in: "query"
        required: false
        type: "string"
      - name: "tgt_date_to"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/SlipList"
        500:
          description: "Internal Error."
          schema:
            $ref: "#/definitions/Empty"
      security:
        - api_key: []
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:055389889595:function:myhome-account-get-slip/invocations"
        responses:
          default:
            statusCode: "200"
          .+:
            statusCode: "500"
        passthroughBehavior: "when_no_templates"
        requestTemplates:
          "application/json" : "{ \"tgt_date_from\": \"$input.params('tgt_date_from')\", \"tgt_date_to\": \"$input.params('tgt_date_to')\" }"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: aws
    post:
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Slip"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      security:
        - api_key: []
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:055389889595:function:myhome-account-post-slip/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: aws_proxy
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
  Health:
    type: "object"
    title: "Health result"
    properties:
      status:
        type: "string"
  Balance:
    type: "object"
    properties:
      tgt_date:
        type: "string"
      value:
        type: "integer"
      memo:
        type: "string"
  KindMst:
    type: "object"
    properties:
      kind_cd:
        type: "string"
      kind_nm:
        type: "string"
      memo:
        type: "string"
      income_flg:
        type: "integer"
  KindMstList:
    type: "array"
    items:
      $ref: "#/definitions/KindMst"
  Slip:
    type: "object"
    properties:
      tgt_date:
        type: "string"
      kind_cd_seq:
        type: "string"
      value:
        type: "integer"
      memo:
        type: "string"
  SlipList:
    type: "array"
    items:
      $ref: "#/definitions/Slip"
