AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 Bucket of CloudFront Origin for My Home Account"
Resources:
  # S3 Bucket For CloudFront Origin
  MyhomeaccountCloudFrontOriginS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "myhome-account-cloudfront-origin-s3-bucket"

  # OriginAccessIdentity
  MyhomeaccountCloudFrontOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: MyhomeaccountCloudFrontOriginAccessIdentity

  # S3 bucket policy to allow access from CloudFront OAI
  MyhomeaccountBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyhomeaccountCloudFrontOriginS3
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub
              - arn:aws:s3:::${BUCKET_NAME}/*
              - { BUCKET_NAME: !Ref MyhomeaccountCloudFrontOriginS3 }
            Principal:
              AWS: !Sub
                - arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${OAI_ID}
                - { OAI_ID: !Ref MyhomeaccountCloudFrontOriginAccessIdentity }

  # Add Policy To S3 Using OAI
  MyhomeaccountDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        IPV6Enabled: True
        DefaultRootObject: index.html
        HttpVersion: http2
        Comment: !Sub ${AWS::StackName}-distribution
        Origins:
        - Id: S3Origin
          DomainName: !GetAtt MyhomeaccountCloudFrontOriginS3.DomainName
          S3OriginConfig:
            OriginAccessIdentity: !Sub
              - origin-access-identity/cloudfront/${OAI_ID}
              - { OAI_ID: !Ref MyhomeaccountCloudFrontOriginAccessIdentity }
        - Id: ApiGatewayOrigin
          DomainName: z6tw2evta4.execute-api.ap-northeast-1.amazonaws.com
          CustomOriginConfig:
            HTTPSPort: 443
            OriginProtocolPolicy: match-viewer
          OriginPath: /dev
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: False
          ViewerProtocolPolicy: allow-all
          SmoothStreaming: False
          Compress: True
        CacheBehaviors:
        - TargetOriginId: ApiGatewayOrigin
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - PATCH
            - POST
            - DELETE
          ForwardedValues:
            Cookies:
              Forward: all
            Headers:
              - Authorization
              - Host
              - Origin
              - Referer
              - Content-Type
            QueryString: True
          ViewerProtocolPolicy: redirect-to-https
          SmoothStreaming: False
          Compress: True
          PathPattern: api/*
          MinTTL: 0
          MaxTTL: 0
          DefaultTTL: 0
Outputs:
  S3BucketName:
    Value: !Ref MyhomeaccountCloudFrontOriginS3
  DistributionId:
    Value: !Ref MyhomeaccountDistribution
  CloudFrontDomain:
    Value: !GetAtt MyhomeaccountDistribution.DomainName
