AWSTemplateFormatVersion: "2010-09-09"
Description: "DynamoDB for My Home Account"
Parameters:
  dynamodbDummyParam:
    Type : Number
    Default : 1
    MinValue: 1
Resources:
  DDBTablemyhomeaccountaccountmethodmst:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "account_method_mst"
      AttributeDefinitions:
        - AttributeName: "method_cd"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "method_cd"
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: "Description"
          Value: "payment method information"
  DDBTablemyhomeaccountaccountbalance:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "account_balance"
      AttributeDefinitions:
        - AttributeName: "tgt_date"
          AttributeType: "S"
        - AttributeName: "method_cd"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "tgt_date"
          KeyType: HASH
        - AttributeName: "method_cd"
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: "Description"
          Value: "balance information of each payment method"
  DDBTablemyhomeaccountaccountkindmst:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "account_kind_mst"
      AttributeDefinitions:
        - AttributeName: "kind_cd"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "kind_cd"
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: "Description"
          Value: "slip kind information"
  DDBTablemyhomeaccountaccountslip:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "account_slip"
      AttributeDefinitions:
        - AttributeName: "tgt_date"
          AttributeType: "S"
        - AttributeName: "kind_cd_seq"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "tgt_date"
          KeyType: HASH
        - AttributeName: "kind_cd_seq"
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: "Description"
          Value: "slip information"
